### ISSUE TITLE
Neos does not render Help message from Yaml file.

### ISSUE THREAD

**Issue by Nikdro** [neos/neos-ui#1694]
The Help message is not rendered by following the guide at http://neos.readthedocs.io/en/3.3/References/PropertyEditorReference.html#property-type-string-textfieldeditor-single-line-text-editor-default.

(Taken from https://github.com/neos/neos-development-collection/issues/1830 @Nguonchhay)

**Comment by dimaip** [comment]
Wow, I was absolutely sure I had implemented it already, but looks like not...

**Comment by cvette** [comment]
Why is this planned only for the Text Editor? Wouldn't something like this make sense for all editors? It could be a small _question-circle_ icon next to the label that shows a tooltip (or just slides in the message) when clicked.

**Comment by dimaip** [comment]
It's not related to any editor, it would be implemented the way it was in the old UI and as documented.

**Comment by cvette** [comment]
You mean the help for the node type itself. But @Nikdro linked the documentation of the _TextFieldEditor_ which shows that you can specify a help message for a node property. That would be nice to have as well.

**Comment by dimaip** [comment]
I know how help messages worked in the old UI (I implemented them). They are supposed to work for any property, just as you have described.

**Comment by kdambekalns** [comment]
@cvette The link posted in the issue is showing the help as a "side effect". The real description can be found on http://neos.readthedocs.io/en/3.3/CreatingASite/NodeTypes/NodeTypeDefinition.html (searc for "help")

**Comment by 2case** [comment]
Any update on this? The help tooltips in the inspector are still missing and one of our customer is still sad about this ;)

**Comment by mstruebing** [comment]
@2case sadly not.
 We will have a sprint next week, maybe it fits in there :)

**Comment by 2case** [comment]
@mstruebing that would be great :) - My knowledge about react and neos ui internals is very limited so i can't really help on this... :(

**Comment by 2case** [comment]
Hello,

i tested it and got some Problems. It seems that the translation is not rendered and no resource:// path resolve happend:

NodeTypes.yaml Part:

```
properties:
   propertyName:
    ui:
      help:
        message: i18n
        thumbnail: 'resource://Vendor.Project.Website/Public/NodeTypes/NodeTypeName/Thumbnail.svg'
```
This result in the following HTML:
```
<div class="style__tooltip-inner___3DM9n">
Vendor.Project.Website:NodeTypes.NodeTypeName:properties.propertyName.ui.help.message
<img alt="Vendor.Project.Website:NodeTypes.NodeTypeName:properties.propertyName" src="resource://Vendor.Project.Website/Public/NodeTypes/NodeTypeName/Thumbnail.svg">
</div>

```
Tested with Version 1.1.2

Greetings,
Tom.

**Comment by mstruebing** [comment]
Sorry, we need to polish this a bit.
I created followup PRs for this
