### ISSUE TITLE
Search in Link Editor (inline and in property inspector) returns TypeError

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#2286]
On current dev-master of neos-ui, typing anything into a LinkEditor results in the following error in the console log:
![image](https://user-images.githubusercontent.com/6552092/51375708-e5c29880-1b06-11e9-9df6-d49b749932b1.png)

After a quick look at the code, it seems that in `Neos.Neos.Ui/packages/neos-ui-backend-connector/src/Endpoints/index.js` the `AssetProxySearch` is called without the option `assetsToExclude`

**Comment by dimaip** [comment]
Awesome, thanks for testing!

**Comment by maya-shines** [comment]
I have a suspicion that it broke with this commit: https://github.com/neos/neos-ui/pull/2161/files
...if that helps?

**Comment by maya-shines** [comment]
@dimaip 4.2.4 in this case

**Comment by daniellienert** [comment]
Seems fixed in current master (posible a mismatch between UI / UI-compiled packages)

**Comment by dimaip** [comment]
Actually I still have this error. Will keep it open for now and then re-test.

**Comment by dimaip** [comment]
Nevermind, indeed it is fixed
