### ISSUE TITLE
PluginView Editor not working again

### ISSUE THREAD

**Issue by pankajlele** [neos/neos-ui#2384]
### Description

PluginView editor not showing selector of available views but shows error in the inspector:
**TypeError: o.get is not a function**

### Steps to Reproduce

1. Add master plugin
2. Add plugin view
3. Select master plugin in the plugin view's inspector

#### Expected behavior

It should show the selector box of views and not error

### Affected Versions

Neos: 4.2.x

UI: 3.x

**Comment by markusguenther** [comment]
Thanks for reporting the issue. It has been fixed during the last code sprint by @samuelhauser
We really appreciate the contributions. 

🙏

**Comment by pankajlele** [comment]
Thank you guys for the fix :) Happy for small contribution.
Will wait for the release to be tagged to rollout update for affected projects.

**Comment by pankajlele** [comment]
@markusguenther @samuelhauser @dimaip I have installed latest UI release 3.3.0 however this issue still persists. But instead of showing error it always shows "No plugin configured". So for my already added PluginViews, the PluginView itself is rendering but in inspector only "No plugin configured" even if the Master Plugin is set. Please help!

**Comment by markusguenther** [comment]
Ok then we will need a bit more investigation time. Thanks for the report and the patient notification:)

**Comment by beardcoder** [comment]
Same issue here. No views are available in the Select Box.
But without an JS Error.

Neos: 4.3
UI: 3.3

**Comment by pankajlele** [comment]
Installed UI 3.4. This bug has gone away. thank you for the great work!
