### ISSUE TITLE
BUG: spacing issues in some parts of the ui

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-ui#3357]
### Description

I noticed that some distances in the neos-ui are no longer as they used to be. I think one of the last changes broke it. I haven't been able to find out which change caused this bug.

Here are a few comparisons

### demo.neos.io

![demoneosio](https://user-images.githubusercontent.com/39345336/218260043-8fd8eebb-8282-4047-b574-74e3fce22f54.png)

![demoneosio1](https://user-images.githubusercontent.com/39345336/218260047-81a500e9-4f5c-4abd-920c-0d8ad9793005.png)

![demoneosio2](https://user-images.githubusercontent.com/39345336/218260488-48cd4149-ab75-4ce6-ae94-56bdfc77e912.png)

![demoneosio3](https://user-images.githubusercontent.com/39345336/218272032-93232c01-2176-495f-93b0-b4a293534ed8.png)

### 8.2.x-dev

![local](https://user-images.githubusercontent.com/39345336/218260056-6d99ecea-d2b6-48a2-9e5e-acd8bfd3e617.png)

![local1](https://user-images.githubusercontent.com/39345336/218260059-c2ebd577-482d-4c96-baa0-f7b63e223f47.png)

![local2](https://user-images.githubusercontent.com/39345336/218260497-1e10dbfa-e5d9-43ef-9864-00f51d8e6a1d.png)

![local3](https://user-images.githubusercontent.com/39345336/218272035-7694e0d8-cd30-4c83-8c52-51b4db7a8426.png)

### Affected Versions

Neos:
8.2.x-dev

UI:
8.2.x-dev

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by Sebobo** [comment]
Can't really reproduce with the 8.2 branch. 
Did you rebuild, and if yes, did you do `make build` or `make build-production` and what is your browser, etc.

**Comment by crydotsnake** [comment]
I used `make setup` which should also build the files. And my browser is chrome.

**Comment by Sebobo** [comment]
Can this be closed now?

**Comment by markusguenther** [comment]
We fixed this and if we find another parts with issues, feel free to reopen ;)
Thanks for reporting @crydotsnake

**Comment by crydotsnake** [comment]
Hm. I updated my `8.3` branch to the latest changes, but it is still broken.
After i pulled the latest changes, i used `make clean && make setup` too have a fresh base.

**Comment by crydotsnake** [comment]
Now it seems to be fixed :)
