### ISSUE TITLE
BUG: CreationDialog shows invalid date with string now as value

### ISSUE THREAD

**Issue by ghost** [neos/neos-ui#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a property with datetime and default value now is shown in creation dialog it shows the error invalid date but once you create the page it shows the correct date in the inspector.

```yaml
    publicationDate:
      type: DateTime
      defaultValue: 'now'
      ui:
        showInCreationDialog: true
```

### Expected Behavior

Shows current date in creation dialog

### Steps To Reproduce

- create a datetime property
- set defaultvalue to now
- set showInCreationDialog to true

### Environment

```markdown
- Flow: 8.1.2 
- Neos: 8.1.2
- PHP: 8.1
```

**Comment by ahaeslich** [comment]
I can also reproduce this behaviour with Neos 7.3

**Comment by PRGfx** [comment]
The date default-value can be any PHP date-string, not just `now`, but for example `today 10 pm`, `tomorrow midnight` or `first day of next month`. So this behavior occurs with these values as well.

I think the UI would have a hard time evaluating this, so maybe the UI should show the format string instead and then let the backend create the value? There could be edge-cases with the UI being opened and between loading and submitting the form for example the value of "today" changes. In these scenarios the node should probably be created with the date shown to the editor (thus evaluated on opening the creation dialog)..

**Comment by mhsdesign** [comment]
ohhh boi ^^ we missed that in https://github.com/neos/neos-ui/pull/3392 but to be hones its odd that we open up this api that much ...

**Comment by JamesAlias** [comment]
@PRGfx Thank you for clarifying that ❤️  We weren't aware of this api when we implemented the fix.

**Comment by mhsdesign** [comment]
Still an issue with the latest beta for Neos 9.2

<img width="740" height="323" alt="Image" src="https://github.com/user-attachments/assets/30458456-3f80-4a7c-96e4-8ea7b0208c5a" />

As we pass the defaultValue straight to PHP it will be hard to implement this fully correctly. I believe still that the api is opened up too much and we should not allow any valid PHP (relative) date string. More complex dates can be set by default via FlowPack.NodeTemplates.

Also as seen by https://github.com/neos/neos-development-collection/pull/5913 setting the default date times is quite a handstand also in our CR to do _correctly_

In our project we will remove the default of "now", _now_ as clicking the date already allows to specify "Today"
