### ISSUE TITLE
Nodes in the page tree only show as hidden when they are selected

### ISSUE THREAD

**Issue by tobiasgruber** [neos/neos-ui#749]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

If a node is set to hidden it is currently displayed normally in the page tree. When it is selected it is updated to display with strike through.

When the page tree is loaded, hidden nodes should display correctly (struck through).

**Comment by mstruebing** [comment]
I can't reproduce it, are you on the latest version of neos and the ui package? Maybe it is fixed in between, could you check again?

**Comment by skurfuerst** [comment]
@mstruebing I've seen it; quite sure it still exists.

1) ensure page A is set to hidden.
2) go to page B.
3) reload the whole backend.
4) ERROR: page A is not displayed as hidden.
5) when selecting Page A (and thus fully loading it), it becomes crossed-out.

The error, I think is, that we do not send the hidden status in the Node Tree endpoint; but we should.

**Comment by tobiasgruber** [comment]
Taken on our website with the new Beta 3: ![neos_reactui_beta3_hidden_nodes_in_tree_bug](https://user-images.githubusercontent.com/15209886/27884970-7ee2150e-61d6-11e7-84cb-97ad013fbe6c.gif)

**Comment by skurfuerst** [comment]
OK, this breaks the system on quite some cases. Will fix this :)
